### ISSUE TITLE
runSpecs producing unexplained "cyclic object value" on Firefox

### ISSUE THREAD

**Issue by chadlwilson** [jasmine/jasmine-browser-runner#18]
Not sure if this is in the right place to report, but when running batch/CI mode with `runSpecs` on Firefox `jasmine-browser-runner` fails with 

```
$ jasmine-browser-runner runSpecs --config=spec/javascripts/support/jasmine-browser.js
Jasmine server is running here: http://localhost:56034
Jasmine tests are here:         /Users/chad/Projects/community/gocd/gocd/server/src/main/webapp/WEB-INF/rails
Source files are here:          /Users/chad/Projects/community/gocd/gocd/server/src/main/webapp/WEB-INF/rails/public/assets
Running tests in the browser...
JavascriptError: Cyclic object value
    at Object.throwDecodedError (/Users/chad/Projects/community/gocd/gocd/server/src/main/webapp/WEB-INF/rails/node_modules/selenium-webdriver/lib/error.js:522:15)
    at parseHttpResponse (/Users/chad/Projects/community/gocd/gocd/server/src/main/webapp/WEB-INF/rails/node_modules/selenium-webdriver/lib/http.js:549:13)
    at Executor.execute (/Users/chad/Projects/community/gocd/gocd/server/src/main/webapp/WEB-INF/rails/node_modules/selenium-webdriver/lib/http.js:475:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async thenableWebDriverProxy.execute (/Users/chad/Projects/community/gocd/gocd/server/src/main/webapp/WEB-INF/rails/node_modules/selenium-webdriver/lib/webdriver.js:735:17) {
  remoteStacktrace: 'WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:183:5\n' +
    'JavaScriptError@chrome://remote/content/shared/webdriver/Errors.jsm:362:5\n' +
    'evaluate.assertAcyclic@chrome://remote/content/marionette/evaluate.js:52:11\n' +
    'evaluate.toJSON@chrome://remote/content/marionette/evaluate.js:323:14\n' +
    'receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.jsm:177:31\n'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It seems to work perfectly fine with
* Firefox and `jasmine-browser-runner serve --config=spec/javascripts/support/jasmine-browser.js`
* `runSpecs` via Chrome (headless and non-headless)

I'm not sure what is different other than reporters, or how to debug further - any tips appreciated.

**Environment**
* OS: MacOS 12.4
* Browser: Firefox 100.0.2
* Geckodriver: 0.31.0
* Dependencies: jasmine-browser-runner@1.0.0 selenium-webdriver@4.2.0

**Comment by sgravrock** [comment]
If I'm interpreting that stack trace right, Selenium is trying to send the result of a command from the browser to the driver, but the result fails to serialize because it contains a cycle. Assuming that the command is part of Jasmine and not internal to Selenium, [this is the likely source](https://github.com/jasmine/jasmine-browser-runner/blob/e688cc302d313eb4bbc0c6169de2d68efb4af8ad/lib/runner.js#L4-L18). That code guards against cycles in the passed and failed expectations, but not elsewhere. I can get the same stack trace if I do something like this:

```
const name = {};
name.loop = name;

it(name, function() {});
```

I assume you're not doing anything like that, but maybe something about your test suite is causing a cycle to appear in an unexpected place. If I'm right, you might be able to find it with a custom reporter:

```
const reporter = {};

for (const method of ['jasmineStarted', 'jasmineDone', 'suiteStarted', 'suiteDone', 'specStarted', 'specDone']) {
  reporter[method] = function(result) {
    try {
      JSON.stringify(result);
    } catch (e) {
      console.error('Reporter method', method, 'got a cyclic result:', result);
    }
  };
}

jasmine.getEnv().addReporter(reporter);
```

Put that in a helper file, then:

1. Make sure it's referenced by the `helpers` field in jasmine-browser.json.
2. Run the `serve` subcommand.
3. Visit the page in the browser and wait for specs to run.
4. Look for errors in the console.

You might get some false positives, since that will flag cycles in expectation results even though those shouldn't cause the error you're getting.

**Comment by chadlwilson** [comment]
Thanks for your reply @sgravrock - I've tried that and I don't see any errors in the console. Also verified the helper/reporter suggested above is being loaded :-(

If it only fails on Firefox and not Chrome, does that point in any particular direction?

**Comment by sgravrock** [comment]
Hmm. I think that points a bit more at the possibility of an internal error in Selenium, but I don't have any idea what would cause that. If you can put together a repo that reproduces the error, I can try to isolate it further.

**Comment by chadlwilson** [comment]
Oof, indeed :-)

> Prototype.js, right? I assume (a) that you know it has security holes that will likely never be fixed, and (b) that removing it would be really hard. Best of luck to you.

I wasn't specifically aware of this, as nothing is being reported against `1.6.0.3` from the various tools we're running but neither am I surprised given its age.

And yeah, although I don't have all the historical background and frontend is not my strong suit, I imagine the reason it is still there is due to the difficulty of removing it. Much of this "legacy" JS has been gradually rewritten into webpacked typescript SPAs alongside a move away from Rails (tested via Karma-jasmine), however there is still stuff left. Was seeing what I could do to keep the testing "lights on" as it were.

**Comment by chadlwilson** [comment]
Be afraid, be very afraid: https://github.com/chadlwilson/gocd/commit/0e395dcbfc2296af4536188f8aba5594b5228193

This will do for now; hacky and I dont really understand why it works, but still both a better experience than with the old Ruby Jasmine monkey-patch (I can get failure details back over the CLI just fine) and at least not using deprecated stuff.

Thanks for your help!
