### ISSUE TITLE
npx jasmine-browser-runner runSpecs doesn't use the port from the configuration file

### ISSUE THREAD

**Issue by DobromirZlatkov** [jasmine/jasmine-browser-runner#21]
https://github.com/jasmine/jasmine-browser-runner/blob/69a18960391d5c302540eefe573a048f2c3e618a/index.js#L79

Most of the CSS, js, and static content for my tests are served from a third-party server, which has a specific CORS configuration, and every time I run the tests I need them to run on the same PORT. There is a "port" option in the jasmine-browser.json but it works only for the "npx jasmine-browser-runner serve" command and not working for "npx jasmine-browser-runner runSpecs". Can you update the code above to read the port from the configuration if is set?

**Comment by sgravrock** [comment]
Having the runSpecs command support the port option sounds like a good feature to have. I'd be happy to review a pull request that adds it.

**Comment by DobromirZlatkov** [comment]
I can't push to this repository (403), so I won't be able to create a pull request. Can you give me access or someone else may handle this?

**Comment by sgravrock** [comment]
Like most OSS projects, we only give direct write access to certain people. [This doc explains how to set up a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request). Basically you need to fork the repo, push your work up to your fork, and then open a PR from there.
