### ISSUE TITLE
Question: Is there an option to override only files ending in `.mjs` to be treated as JS modules?

### ISSUE THREAD

**Issue by nathan-barrett** [jasmine/jasmine-browser-runner#22]
Hello!

Just wondering if there would be a property in the config that I can set to treat certain files as es modules. 

For example for mozilla.org's repo - we name JS modules with `*.es6.js`. If you feel like this could be a helpful change, I would also be more than happy to make a PR for this - if someone would be able to point me in the correct direction? Thanks!

**Comment by sgravrock** [comment]
There's nothing that does that now, but a PR would be welcome. The touch points that I'm aware of are the [spec file filtering in server.js](https://github.com/jasmine/jasmine-browser-runner/blob/69a18960391d5c302540eefe573a048f2c3e618a/lib/server.js#L80) and the [extension check in run.html.ejs](https://github.com/jasmine/jasmine-browser-runner/blob/69a18960391d5c302540eefe573a048f2c3e618a/run.html.ejs#L17). You can also find relevant specs by searching for `.mjs`.
