### ISSUE TITLE
Getting "This site can’t provide a secure connection"

### ISSUE THREAD

**Issue by benlieb** [jasmine/jasmine-browser-runner#25]
http://localhost:8888/ redirects to https://localhost:8888/

This site can’t provide a secure connection
localhost sent an invalid response.
ERR_SSL_PROTOCOL_ERROR

Not sure if this is my side or yours...

Using Chrome browser

**Comment by sgravrock** [comment]
That's unlikely to be caused by jasmine-browser-runner. More likely you're running into something like [this](https://stackoverflow.com/questions/25277457/google-chrome-redirecting-localhost-to-https), or some other form of cached permanent redirect.
