### ISSUE TITLE
ES module testing and import maps

### ISSUE THREAD

**Issue by wraiford** [jasmine/jasmine-browser-runner#28]
## tl;dr

Is there an existing mechanism that I'm not seeing for import maps specifically? Or is there a more generic way to inject code into the `run.html.ejs` file?

## context

I'm looking to build multiple packages and exploring options to try to minimize complexity. Currently I have jasmine working with testing ES modules in both node and in the browser in my base package with no imports with bare references. But as soon as I try to consume my base package in another package and test, I am unable to do so in the browser context (it works in node jasmine) since the browser does not know how to resolve the reference.

```typescript
import { clone } from 'ts-gib';
```

succeeds in node jasmine but produces an error in the browser: 

> Uncaught TypeError: Failed to resolve module specifier "ts-gib". Relative references must start with either "/", "./", or "../".

## workaround

If I manually modify my `node_modules/jasmine-browser-runner/run.html.ejs` to include an `importmap` script tag and then execute the jasmine-browser-runner (either `runSpecs` or `serve`), it works as expected.

```html
<script type="importmap">
  {
    "imports": {
      "ts-gib": "https://unpkg.com/ts-gib@0.4.3/dist/browser/index.mjs"
    }
  }
</script>
...other script tags
```

> Started
> .
> 1 spec, 0 failures

## additional comments

As an aside, with so much movement towards ES modules (even [TypeScript v5 will be using them internally](https://devblogs.microsoft.com/typescript/typescripts-migration-to-modules/)), I think this could be a huge opportunity going forward for whoever makes testing in both node and browsers with ES modules the easiest. The landscape is ever changing of course, but at the very least [import maps seem to have been standardized in most browsers](https://caniuse.com/import-maps).

**Comment by sgravrock** [comment]
That seems like a useful feature. I think it'd be better to let users specifically configure an import map than to provide a general way to inject code into the template. Partly because I think it'll make a useful capability more obvious, and partly because it doesn't create the risk of us breaking user configurations if we change the HTML in the template. Want to submit a PR?

**Comment by wraiford** [comment]
Eesh, I've been meaning to "help" another online project, especially one that I rely on (I try to minimize deps for better or worse 😬 ). I'll see what I can come up with. 

How would you think the consumer would provide the imports:

1. entry in the `jasmine-browser.json` config
2. html file
3. js/ts file

Since the import map in the `script` tag is itself a key/value, I would imagine (1) would be the most natural fit.

As for the actual injection pieces, do you have an idea where in the codebase you would do it? I've grokked the overall structure, but I do relatively little with raw JS and more have viewed it through the TS transpilation lens these past several years. Also there's always little nooks and crannies in mature code bases it seems. 🙄

**Comment by sgravrock** [comment]
> How would you think the consumer would provide the imports:
> 
>     1. entry in the jasmine-browser.json config
>     2. html file
>     3. js/ts file
> 
> Since the import map in the script tag is itself a key/value, I would imagine (1) would be the most natural fit.

Yes. That seems like it'd be both best for users and easiest to implement.

> As for the actual injection pieces, do you have an idea where in the codebase you would do it? I've grokked the overall structure, but I do relatively little with raw JS and more have viewed it through the TS transpilation lens these past several years. Also there's always little nooks and crannies in mature code bases it seems. 🙄

You shouldn't really need to wire anything up, because the configuration is already passed to the `Server` constructor more or less unmodified. I think these are the parts of the code that would need modification:

* `run.html.ejs` to actually output the import map.
* `server.js` to provide the import map to `run.html.ejs`.
* JSDocs for `Configuration` in `types.js`.
* Tests for the new functionality.

**Comment by wraiford** [comment]
I've done a [small commit for just the validation of the config (and specs)](https://github.com/jasmine/jasmine-browser-runner/compare/main...wraiford:jasmine-browser-runner:main) (although rereading your msg, I see the `config.js` wasn't there! 😬 ). Could be too heavy for you in terms of validation, I just am in the camp of it's hard to have too much.

I included notes in the git commit message, but basically I just want to see your opinions on the overall style and such. I know you're busy, so I'll go ahead and start sometime this week on the other pieces. But since it's early days, it's better to get stylistic decisions top-down early so I can hopefully minimize those kinds of changes. I am naturally more verbose than most programmers, and I'll need help to try to speak your language better. I am mainly thinking of the consumer's POV and it helps knowing if you do a silly mistake like an empty string key or something (which doesn't make sense for an import map afaict).

**Comment by wraiford** [comment]
I've gone ahead and pushed what I have for the `types.js` in [this commit](https://github.com/jasmine/jasmine-browser-runner/commit/8a32d78d713eb2027033e400007379c2610480dd).

I am not an expert with jsdoc (more proficient with TS), but I've tried to emulate existing code. I was unsure if jsdoc allowed nested object definitions:

```javascript
/**
 * Map of one or more scoped module specifier maps.
 * @name ImportMappingsInfo#scopes
 * @type {Object.<string, Object.<string, string>>}
 */
```

_note: I have since changed the `ImportMapping` to `ImportMap` in various places, as this seems to make more sense from the consumer's POV._

I'm still working on the import map ejs injection and testing.

**Comment by sgravrock** [comment]
That look pretty good for the most part, with a couple of things that I'd change. Responding to some of your questions first:

> Could be too heavy for you in terms of validation, I just am in the camp of it's hard to have too much.

More validation seems better to me as long as it doesn't go too far and reject invalid import maps. What you have here seems fine, at a glance.

>  I was unsure if jsdoc allowed nested object definitions:

I tried out the example you gave and it seemed to work. In any case, if there are minor jsdoc syntax issues I can fix them post-merge.

> note: I have since changed the ImportMapping to ImportMap in various places, as this seems to make more sense from the consumer's POV.

Agreed. Import Map seems to be the commonly used term, so going with that makes sense to me.

Some stylistic issue:

* In Jasmine, the public API reference docs are autogenerated from JSDoc comments. Since `validateImports` and `errorMsgHas` aren't part of the public API, they shouldn't have JSDoc comments. Feel free to keep a comment that does *not* start with `/**` if you like, but in general I find that the JSDoc style formality is overkill for internal functions that only have one or two nearby call sites.
* I think that it would be better to remove the `const k = 'importMappings'` variable in config.js. It adds indirection, which imposes a cost every time anyone reads the code in the future, and I'm not convinced that it's carrying its weight.
* Similarly, the specs would be more readable if the `kName` variable removed.

**Comment by wraiford** [comment]
Ah, thanks for the input. These are definitely the types of local choices to learn early on.

> More validation seems better to me as long as it doesn't go too far and reject invalid import maps. 

I'm assuming you mean reject valid import maps and I agree. I just have a habit of writing more tests than necessary while developing and feeling out wth I'm doing, but eventually it accumulates and can cost in overall test execution time. It's always easier to remove what we see as superfluous tests in the end. But I see this as your call. The point here is that there is an import map spec, and we can:

1. Commit to verifying the entire spec, including various and sundry like allowing for empty maps and ensuring trailing slashes match in both keys/values.
2. Give next-to-no validation other than defensive injection validation from our POV.
3. Give some easy low-hanging fruit with regards to verification of the consumer's import maps (like empty keys), so we can give them a little nudge with a helpful error message in case they forget something.

Obviously I went with no. 3, but this may give a false sense of security if the consumer thinks that it's a full verification.

Btw, WRT to no. 2 defensive injection validation, is there such a worry with this? Or more generally, besides your earlier point of not allowing arbitrary injection into the html template, is there another validation check I should be doing? I don't know all of the scenarios that jasmine is used or how this could be wielded, but I'd be glad to add in more regexp checks/whatever if needed. I don't think encoding would be good, but maybe something that disallows for anything to contain the string `'<script>'` sounds like it might be good. But like you said, I'd hate to have a valid mapping fail (annoyingly from the consumer's POV).

> In Jasmine, the public API reference docs are autogenerated from JSDoc comments. Since `validateImports` and `errorMsgHas` aren't part of the public API, they shouldn't have JSDoc comments. Feel free to keep a comment that does not start with /** if you like, but in general I find that the JSDoc style formality is overkill for internal functions that only have one or two nearby call sites.

I am from the TS-vscode world and do it largely for my own auto-completion and a signature reference during dev, as opposed to document generation. Vscode also enables easy jsdoc generation WRT the `/**/` style comments, but I am not trying to sway you on this or anything. Besides, I found that `toThrowError` has a regexp overload so I was able to simplify here. You can see the changes [here](https://github.com/jasmine/jasmine-browser-runner/commit/4b1bdcb5f4b83b2b7672a9edbc0fa223f517cb09), as well as other cleanup. Hey it's cool that I'm getting a better look into the api for my own usage too.

> I think that it would be better to remove the const k = 'importMappings' variable in config.js. It adds indirection, which imposes a cost every time anyone reads the code in the future, and I'm not convinced that it's carrying its weight.
> Similarly, the specs would be more readable if the kName variable was removed.

Yes, it's hideous! You can say it I don't mind! (But I appreciate your being polite here for sure). I have that in there for the [2nd of 2 hard problems in CS](https://martinfowler.com/bliki/TwoHardThings.html). Early on it's nice to have the refactoring capability with interpolated strings like that and not just rely on a regex find/replace which can be scary in brownfield (from my POV) projects. The commit for this cleanup can be found [here](https://github.com/jasmine/jasmine-browser-runner/commit/625c13de6b943ceca8d0ba800f128162d92c5b1d).

**Comment by sgravrock** [comment]
> Btw, WRT to no. 2 defensive injection validation, is there such a worry with this? Or more generally, besides your earlier point of not allowing arbitrary injection into the html template, is there another validation check I should be doing? I don't know all of the scenarios that jasmine is used or how this could be wielded, but I'd be glad to add in more regexp checks/whatever if needed. I don't think encoding would be good, but maybe something that disallows for anything to contain the string '<script>' sounds like it might be good. But like you said, I'd hate to have a valid mapping fail (annoyingly from the consumer's POV).

The short answer is that I think the validation you already have is sufficient, and I wouldn't go farther than that.

The longer answer:

My concerns here aren't about security. As Raymond Chen would put it, "it rather involved being on the other side of this airtight hatchway": anyone who can edit the config file already has full control of the system. My concerns are more about defining clear expectations for the public API. If we provided a mechanism that was designed to insert arbitrary HTML, people might be reasonably upset if a future version broke compatibility with their particular HTML. But if we provided a mechanism that's clearly designed to insert an import map and somebody found a way to abuse it to inject arbitrary HTML, I don't think they could reasonably expect future compatibility. I think that's firmly in "if it breaks, you get to keep both pieces" territory.

And even if security *was* a concern, it's better to encode output safely than to filter input. (A parallel: Trying to prevent SQL injection by filtering out single quotes both falls short from a security standpoint and prevents people named O'Neil from using the system.) In this case ejs should take care of output encoding properly as long as you use `<%= %>` and not ` <%- %>`.

**Comment by wraiford** [comment]
Yes that is about what I had thought also,  although with regards to this: 

> anyone who can edit the config file already has full control of the system

I started with this viewpoint also, but then I considered if open source collaboration has changed this. Certainly there have been larger- than-ideal commits on projects with strained resources,  where there aren't enough eyes & brains able to see and evaluate each line. A lot inevitably falls down to trust often,  and there are always long cons willing to build that. Even the Linux kernel [was vulnerable](https://www.theverge.com/2021/4/30/22410164/linux-kernel-university-of-minnesota-banned-open-source) to this type of commit engineering. From that author: 

> But — [as is always the case with crowdsourced operations](https://gizmodo.com/a-teen-threw-scots-wiki-into-chaos-and-it-highlights-a-1844851959) — there’s room for human error.

"Crowdsourced" of course being the more generic hypernym of open source programming. 

That said, I'm a big fan of sovereignty and the responsibility would ultimately be down to the maintainer of the consuming codebase. And it's _your_ sovereign (& awesome) library here so no worries. I'm just trying to talk things out instead of inserting my opinions willy nilly in code. 

Still, I'll look more into the ejs binding and see what you get for free.

**Comment by sgravrock** [comment]
Please open a PR, even if you're not ready for final review. Some of your questions will be easier to address if I can run your code. All of them will be easier if I can see all your work in one place instead of having to piece it together from individual diffs.

> I'm not quite certain how to execute the specs in this project though.

`npm test` runs the test. You'll need to have ChromeDriver installed.

**Comment by wraiford** [comment]
> `npm test` runs the specs. You'll need to have ChromeDriver installed.

Haha! 🤣  No I have been running those specs before each of my commits, as well as adhering to the `prettier` and linting errors. What I mean is that I am not sure how to run the fake specs in [the sample consumer project](https://github.com/jasmine/jasmine-browser-runner/commit/388509dc693e117e4eca8086854d3bbb2b07bd37) I mentioned _inside_ the specs that are run via `npm test`. I thought I made this clear with mentioning [`esmIntegrationSpec.js`](https://github.com/jasmine/jasmine-browser-runner/blob/main/spec/esmIntegrationSpec.js). In that spec file, it has the following code [on line 15](https://github.com/jasmine/jasmine-browser-runner/blob/main/spec/esmIntegrationSpec.js#L15) which looks to be executing an instance of node inside of a spec, using the current working directory of the example project:

```typescript
const jasmineBrowserProcess = exec(
        'node ../../../bin/jasmine-browser-runner runSpecs',
        { cwd: 'spec/fixtures/esmIntegration' },
        function(err, stdout, stderr) {
          try {
            ...
```

It looks like it's just spinning up a node within the spec and testing against std output. I haven't had a chance to try to cargo cult this spec with my sample project but I'll try to get to that going mimicking the above code (unless there's a better way) and start the PR this weekend or Monday. I apologize for not starting the PR, I thought that you could indeed already run the code from my fork.

**Comment by wraiford** [comment]
Sorry I couldn't get the finished PR yesterday, but I was able to get it this morning. 

I point you to the commit comments [here](https://github.com/jasmine/jasmine-browser-runner/commit/53371ebc00519e58d6a64606a8024fccb518be52), which I'll copy paste here inline for convenience:

> importMap sample project specs executing
> 
> * by this, I mean that the specs **within** the sample project
>   are executing dynamically.
>   * this was cargo culted from `esmIntegrationSpec.js`
> * the sample project's specs include using both a bare import that
>   maps directly to a fake library's `index.mjs` file, as well as
>   a pathed import that maps to a path within the fake library.
>    ```
>    "some-lib": "./__src__/node_modules/some-lib/dist/index.mjs",
>    "some-lib/": "./__src__/node_modules/some-lib/dist/",
>    ```
> * there are several things to resolve here:
>   1. currently I included an absolute path in the import map that
>      points to a cdn, which means every time a test is run it is
>      pinging the cdn (or at least the first run before its cached):
>      * "helper-gib": "https://cdn.jsdelivr.net/npm/@ibgib/helper-gib@0.0.4/dist/index.mjs"
>   2. I had to move the sample project's `node_modules` to inside the `src`
>      folder because I did not know how to point the import map such that
>      the it could find the `node_modules` folder in the sample project without
>      doing this and using `__src__` in the map's value:
>      * "some-lib": "./__src__/node_modules/some-lib/dist/index.mjs"
>   3. Even if there were a `__node_modules__` specifier, I dont think the consumer
>      should have to use one of these magic strings (which I don't know enough about).
>      They should be able to use something just like (I think):
>      * "some-lib": "./node_modules/some-lib/dist/index.mjs"

So it's working using the unencoded json string of the import map for sure with the reference to an absolute URL, e.g. `https://cdn.jsdelivr...`. I don't expect us to keep this code when executing the tests, but it might be good to keep commented out as an example for the consumer using our tests as documentation (I know I do). I can change the reference to point to jasmine or jasmine-core, but I don't have a good candidate for a simple function to import from it. If you want to offer up a simple function that you know is exported, I'll make that change and remove the references to `helper-gib`.

I'm also not quite sure about the magic strings like `__spec__` and `__src__` throughout, as I couldn't figure out where that magic happens. I've seen code like that used in webpack before, but it's been awhile, and I'm not sure if we care if the user has to use them in the imports. Since it's within a jasmine config file, it may actually be an acceptable expectation, as long as we document it clearly.

**Comment by sgravrock** [comment]
> So AFAICT, ejs is mainly good at working with iterating over entire tags, as you've done in the existing injection sites in the run.html.ejs file (css <link> tags and js <script> tags for various js files).
> 
> I have it "working" with binding to an unencoded stringified call:
> ```
>   <% if (importMap) { %>
>    <script type="importmap">
>    <%- JSON.stringify(importMap, null, 2) %>
>    </script>
>  <% } %>

Indeed. Contrary to what I said earlier, `<%= %>` doesn't work in this case. If one of the paths in the import map is `./__src__/</script>/index.mjs`, `<%= %>` outputs invalid JSON. So does replacing `<script` with `\x3C/script`  [as recommended by the HTML standard](https://html.spec.whatwg.org/multipage/scripting.html#restrictions-for-contents-of-script-elements). I might just be  missing a trick here, but there might not be a way to encode `</script` that's both valid JSON and safe for embedding in a script tag.

Given that we're only processing trusted input, I think it's OK to use `<%- JSON.stringify(...` like you've done.

> Haha! 🤣 No I have been running those specs before each of my commits, as well as adhering to the prettier and linting errors. What I mean is that I am not sure how to run the fake specs in the sample consumer project I mentioned inside the specs that are run via npm test. I thought I made this clear with mentioning esmIntegrationSpec.js. In that spec file, it has the following code on line 15 which looks to be executing an instance of node inside of a spec, using the current working directory of the example project: [...]

Are you trying to run them interactively for debugging purposes? What I usually do is cd into the fixtures directory and run the same command that the integration test would run, but with `serve` (or no argument) instead of `runSpecs`:

```
$ cd spec/fixtures/integration
$ node ../../../bin/jasmine-browser-runner serve
```

> currently I included an absolute path in the import map that
> points to a cdn, which means every time a test is run it is
> pinging the cdn (or at least the first run before its cached):
>
>    "helper-gib": "https://cdn.jsdelivr.net/npm/@ibgib/helper-gib@0.0.4/dist/index.mjs"

I'd be inclined to remove that. If I understand correctly, having it there mainly verifies that we pass HTTP URLs through to the template correctly. That could probably be checked with a unit test that verifies the HTML, or even one that just verifies that a config containing a URL isn't rejected. That way the tests wouldn't depend on the CDN being up and returning the correct content.

Regarding node_modules, I agree that making people stick node_modules in src is... suboptimal to say the least. So is requiring import maps to contain `__src__`. There's some complexity here that I didn't appreciate until now. For context, the `__spec__` and `__src__` URL prefixes are used to disambiguate/deconflict between specs, src files, and jasmine-browser-runner's own resources. All of this is currently handled in server.js which both [includes the special prefixes in URLs](https://github.com/jasmine/jasmine-browser-runner/blob/f0ef8a45a6200ee9dcce7eff9ceb580cea955b76/lib/server.js#L97-L100) and [uses them to map requests back to files](https://github.com/jasmine/jasmine-browser-runner/blob/f0ef8a45a6200ee9dcce7eff9ceb580cea955b76/lib/server.js#L135-L138). They're visible to users but users don't have to know about them, and I agree that it would be best to keep it that way. One option might be to have the user specify paths that are relative to the project base dir, and then jasmine-browser-runner maps them to URLs that have special prefixes, so e.g. this configuration file:

```
[...]
  "srcDir": "src",
  "importMap": {
    "imports": {
      "foo": src/foo.mjs",
      "bar"/: "./node_modules/bar/dist/",
      "helper-gib": "https://cdn.jsdelivr.net/npm/@ibgib/helper-gib@0.0.4/dist/index.mjs"
    }
  }

```

Produces this HTML:

```
<script type="importmap">
{
   "imports": {
      "foo": "./__src__/foo.mjs",
      "bar"/: "./__node_modules__/bar/dist/",
      "helper-gib": "https://cdn.jsdelivr.net/npm/@ibgib/helper-gib@0.0.4/dist/index.mjs"
   }
}
</script>
```

Another option might be to have a single configurable "lib" directory, which would be node_modules in the case of projects that get their front end libraries from NPM., and then prefix any import map path that's not a URL with __lib__:

```
[...]
  "libDir": "node_modules",
  "importMap": {
    "imports": {
      "bar"/: "/bar/dist/",
      "helper-gib": "https://cdn.jsdelivr.net/npm/@ibgib/helper-gib@0.0.4/dist/index.mjs"
    }
  }

```

```
<script type="importmap">
{
   "imports": {
      "bar"/: "./__node_modules__/bar/dist/",
      "helper-gib": "https://cdn.jsdelivr.net/npm/@ibgib/helper-gib@0.0.4/dist/index.mjs"
   }
}
</script>
```

That would allow first class support for systems like Rails 7 that don't necessarily put their JS library dependencies in node_modules.

Come to think of it, is there actually a use case for import maps that refer to files in the src directory? Or does that need go away entirely if we handle node_modules well?

**Comment by wraiford** [comment]
> Given that we're only processing trusted input, I think it's OK to use `<%- JSON.stringify(...` like you've done.

:+1:

> Are you trying to run them interactively for debugging purposes?

No. Although I did have to debug while making the sample project, it is not the reason for it. I fervently believe with all of my religious coding heart that a _working_ consumer project was essential and we were not just testing for HTML output that "should work". As such, I was glad that taking the esm integration as a template worked well. When I did need to debug, I [changed the `runSpecs` to `serve`](https://github.com/wraiford/jasmine-browser-runner/blob/53371ebc00519e58d6a64606a8024fccb518be52/spec/importMapSpec.js#L19) in the test code (basically doing the same thing you recommend but started via `fit`/`fdescribe`). I think your using the term "integration test" was probably the term I should have used from the start. Being hyperfocused on it "just working" when the consumer goes to use it, I think this integration test is vital.

> I'd be inclined to remove that. ...

I may not have stated it very well, but this is what I was talking about with...

> I don't expect us to keep this code when executing the tests, but it might be good to keep commented out as an example for the consumer using our tests as documentation (I know I do).

In my ESM + import map research (it's new to me!), many examples I see use absolute CDN maps. I was saying that I think it should be in the example project, but commented out so that it does *not* execute. When I am using an open-source library, I often use their unit tests (and integration/e2e if they exist) to see how the api is _actually_ used. The fragmented documentation versioning problem is extremely frustrating for me (and is actually one of the many reasons I am implementing version control with my ibgib library, which at its heart has a very similar structure to git's internals). These unit tests are often a great source of up-to-date documentation directly linked to the actual versioned api. So I would leave in a commented out entry like `"jasmine-core": "https://some.cdn.link.to.jasmine-core/index.mjs"`. But I wanted it to be a working link with a working unit test triggered by a working integration test! But I couldn't come up with a dead-simple function to export from the jasmine-core library, because I'm not intimately familiar with what is exposed. I thought you might be able to proffer a simple function that I could use. For example, in the [sample project](https://github.com/wraiford/jasmine-browser-runner/tree/main/spec/fixtures/importMap), I have an example consumer's unit test that [imports and consumes the `helper-gib` library](https://github.com/wraiford/jasmine-browser-runner/blob/main/spec/fixtures/importMap/spec/aSpec.mjs#L3) like this:

```typescript
import { pretty } from 'helper-gib'; // uses absolute map -> "helper-gib": "https://cdn.jsdelivr.net/npm/@ibgib/helper-gib@0.0.4/dist/index.mjs"

...

it('should consume helper-gib pretty', () => {
    let x = {
        a: 'aaa',
        b: 'bbbb',
        c: '1234c'
    };
    let prettyString = pretty(x);
    console.log(prettyString)
    expect(prettyString).toBeTruthy();
});
```

So `pretty` is just a little, self-contained utility function. Is there a function in `jasmine-core` that you could recommend I import and consume in a test? Then we would comment these tests out, but leave them so that a consumer browsing through the tests would see it. And we know that it works because it does work in the integration test...it's just commented out. Of course this also has the danger of getting out of sync, but it's necessary because of the points you mention. We don't want to rely on whatever cdn we choose to be up (I've already had to deal with mystery errors because a cdn was down, which was annoying!), and really we don't want to be pinging external sites every time a unit test run executes on a ci/whatever server or on a user's machine. 

> All of this is currently handled in server.js which both [includes the special prefixes in URLs](https://github.com/jasmine/jasmine-browser-runner/blob/f0ef8a45a6200ee9dcce7eff9ceb580cea955b76/lib/server.js#L97-L100) and [uses them to map requests back to files](https://github.com/jasmine/jasmine-browser-runner/blob/f0ef8a45a6200ee9dcce7eff9ceb580cea955b76/lib/server.js#L135-L138).

Thank you! I saw those code pieces but couldn't understand what's going on. Now I see the missing piece was express's `use` function. So in that you're providing the mapping of the magic string to the actual filepath. 

> That would allow first class support for systems like Rails 7 that don't necessarily put their JS library dependencies in node_modules.
> Come to think of it, is there actually a use case for import maps that refer to files in the src directory? Or does that need go away entirely if we handle node_modules well?

I am still a beginner in the ESM + import map world, so I can't speak to enterprise production-ready nuances. As such I think we may have to adapt for other unforeseen use cases in the future. That said, it appears that CDN and/or selective `node_modules` publishing are the two approaches I've seen. But there could be other folders that contain map targets. For example, on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#importing_modules_using_import_maps), they give this:

```html
<script type="importmap">
  {
    "imports": {
      "shapes": "./shapes/square.js",
      "shapes/square": "./modules/shapes/square.js",
      "https://example.com/shapes/": "/shapes/square/",
      "https://example.com/shapes/square.js": "./shapes/square.js",
      "../shapes/square": "./shapes/square.js"
    }
  }
</script>
```

So as you've indicated, there are multiple paths forward (pun intended) in how to resolve this (yes, another pun intended...this has been a long Sunday post 😬). I like your `lib` option but in ESM jargon, I think these are modules rather than libs. So I would name it `moduleRootDir` and put this inside the `importMap` config setting. This would mean creating a sub-option name for the actual map itself, either `map` or `importMap`. Then any module specifier targets (the map's values, not keys) that start with `./` get transformed to use the magic string `'__esmodules__'` to parallel the other magic strings' names. And we add a line with the express:

```javascript
app.use('/__esmodules__', express.static(this.importMap.moduleRootDir));
```

Specifier targets that start with `http(s)://` don't get transformed and I'm not sure what to do about `../` (trying to path out of the root directory). 

I think this would cover the Rails scenario, but we would have to add a test specifically for that if we want to be sure. At the very least, I could implement this in the coming week (🤞) and be sure that it works for the simplest case!

I know this was a long post, but thanks for working with me on this!

**Comment by sgravrock** [comment]
> Is there a function in jasmine-core that you could recommend I import and consume in a test?

Nope. jasmine-core isn't an ES module, it's a (slightly weird) CommonJS module. So it won't work in this case. 

>  I like your lib option but in ESM jargon, I think these are modules rather than libs. So I would name it moduleRootDir and put this inside the importMap config setting.

Agreed. `moduleRootDir` is a better name. Putting it in `importMap` feels a little odd at first glance but it makes it really obvious what the setting is for.

> Then any module specifier targets (the map's values, not keys) that start with ./ get transformed to use the magic string '__esmodules__' to parallel the other magic strings' names. And we add a line with the express:
>
> app.use('/__esmodules__', express.static(this.importMap.moduleRootDir));
> 
> Specifier targets that start with http(s):// don't get transformed and I'm not sure what to do about ../ (trying to path out of the root directory).

A slight tweak:
* Disallow ../
* Pass http(s):// through unchanged, as you said
* Treat everything else as relative to moduleRootDir, so './' is not required

I think that would be a reasonable starting point and give a fairly nice API for the use cases we know are out there. I'm a little skeptical that the MDN example you gave is going to be relevant to Jasmine (most likely, import maps won't be required for modules that are part of the codebase being tested). But we can always start small and expand to e.g. multiple module root directories later in response to user feedback.

**Comment by wraiford** [comment]
Ok, I've just pushed the new commit [here](https://github.com/jasmine/jasmine-browser-runner/commit/94b1ccd7dfe0eefb6e311898ee8616d60d83c4ed).

Again for convenience, the commit notes:

> 
> implemented and added/adjusted specs `moduleRootDir` as discussed in issue
> 
> * added parallel existing `imports` and `scopes` options inside `importMap`
>   config option.
>   * this as opposed to moving the `imports` and `scopes` inside of another
>     key like `map` to avoid unnecessary complexity.
> * config.js
>   * added validation for `importMap.moduleRootDir`
>     * empty string and starts with '../' are both invalid
> * server.js
>   * `importMap()`
>     * adjusted bound `importMap()` to transform relative specifiers to use the
>     new `__moduleRoot__` mapping exposed in express app.
>   * `start(...)`
>     * added `__moduleRoot__` mapping logic to express `app.use(...)`
>       * defaults to `projectBaseDir` if not explicitly specified in config
>   * `reifyRawSpecifierMap(rawSpecifierMap)`
>     * helper function for transforming the import map config specifiers to ones
>       that include `__moduleRoot__` (for relative specifier paths only)
> * types.js
>   * added documentation for `moduleRootDir` option.
> 
> * configSpec.js
>   * added config validation if `moduleRootDir` set
> * fixtures/importMap
>   * moved example `node_modules` back to where it normally is.
>   * using `jasmine-browser.json` as example with no `moduleRootDir` explicitly
>     set.
>     * adjusted specifiers to start with `node_modules/`
>   * added `jasmine-browser.module-root-dir.json` that sets `moduleRootDir` to
>     `node_modules`
>     * specifiers here start with the lib itself so `node_modules/` isn't
>       necessary for any of the relative specifiers.
> * importMapSpec.js
>   * added another test that specifies the `jasmine-browser.module-root-dir.json`
>     config.
> * serverSpec.js
>   * adjusted test code that looks at html output to account for transformations
>     of non-absolute pathed specifiers (paths that don't start with "http(s)://")

I have not yet tested it beyond the specs, so I can't say that there isn't something stupidly simple I'm missing. I'll go ahead and test it in my own use case. Let me know what else you need from me or any other feedback, as I'm feeling already a little code blind...I ain't as young as I used to be!

**Comment by wraiford** [comment]
Oh I didn't change the `helper-gib` references. I was thinking of maybe changing it to something more ubiquitious like `lodash-es` or `rxjs` (and then comment it out as mentioned).

**Comment by wraiford** [comment]
Here is a list of manual tests I've run in an actual consuming project (via `npm link`):

* invalid config
  * imports as a string, number
    * threw expected errors
* valid
  * absolute specifier 
    * target is a cdn URL
    * worked as expected
  * relative specifiers
    * no `moduleRootDir` specified
      * project base dir used implicitly
      * import map targets in the form of `node_modules/mypkg/dist/index.mjs` and `node_modules/mypkg/`
      * worked as expected
    * `moduleRootDir` set to `'node_modules'`
      * import map targets in the form of `mypkg/dist/index.mjs` and `mypkg/`
      * worked as expected

So, I feel better seeing these basic consumption tests working on my machine! I'm going to change the `helper-gib` cdn test cases to something else now and make sure they pass. After that, I'll comment them out and annotate what they're doing there. You're welcome to take that out if you feel it's out of place.

**Comment by wraiford** [comment]
All right, I've made those adjustments switching to a `lodash-es` example with [this commit](https://github.com/jasmine/jasmine-browser-runner/pull/30/commits/81bc1d9dfb837ee9e1be71e7b93f8488b791065b). I did test the spec that actually did the importing of lodash from the cdn before commenting them out and it was working.

So, afaict that's it on my end. Let me know if there is something I'm missing here or if you need anything else from me.

**Comment by sgravrock** [comment]
Thanks. I'll provide further feedback on the PR itself.

**Comment by sgravrock** [comment]
Possibly of interest: this feature also allows for a limited form of module mocking.

jasmine-browser.json:
```
{
 [...]
  "importMap": {
    "moduleRootDir": "stubs",
    "imports": {
      "anOtherMod": "./anOtherMod.mjs"
    }
  }
}
```

src/aMod.mjs:
```
import {foo} from 'anOtherMod';

export default function bar() {
	return foo();
}
```

stubs/anOtherMod.mjs:
```
export const foo = jasmine.createSpy('foo');
```

spec/aSpec.mjs:
```
import bar from '../src/aMod.mjs';
import {foo} from 'anOtherMod';

describe('module mocking demo', function() {
	afterEach(function() {
		foo.and.stub();
		foo.calls.reset();
	});

	it('can control the behavior of foo', function() {
		foo.and.returnValue(42);
		expect(bar()).toEqual(42);
	});

	it('would be affected by the previous test if foo was not reset', function() {
		expect(bar()).toBeUndefined();
	});
});
```

This has some pretty significant limitations:

* The stub mapping is global rather than something that can be controlled on a per-spec or per-spec-file basis
* Exported module properties remain immutable.
* State "leaks" from spec to spec unless the spy is manually reset.

But I expect it's a lot better than nothing for people who want to test ES module code and don't want to use dependency injection.

**Comment by HolgerJeromin** [comment]
> The stub mapping is global rather than something that can be controlled on a per-spec or per-spec-file basis

Just in case to do not knew that: 
Instead of having `imports` in your importmap you also can have `scopes` which can be used for some kind of per-spec basis config.

```json
{
  "scopes": {
    "/someSpecificSpecFolder/": {
      "anOtherMod": "./anOtherMod.mjs"
    }
  }
}
