### ISSUE TITLE
How to use external library loaded into the global scope?

### ISSUE THREAD

**Issue by duvifn** [jasmine/jasmine-browser-runner#34]
Hi,
I'm now trying jasmine in browser to test library that can run only in browser.

My question:
In [rollup](https://rollupjs.org/configuration-options/#output-globals) and other build environments, there is an option to indicate usage of global libraries that are loaded using `<script>` tag in the webpage.
How can I include such a global in the spec so it would be loaded by the `jasmine` into the webpage during the spec running?

**Comment by sgravrock** [comment]
You can add the URL to `srcFiles` in your config file, e.g.:

```
  "srcFiles": [
    "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js",
    "**/*.js"
  ],
```

**Comment by duvifn** [comment]
Thanks a lot, @sgravrock! This works to me.
