### ISSUE TITLE
ability to specify a configuration filename other than jasmine-browser.json

### ISSUE THREAD

**Issue by bicarbon8** [jasmine/jasmine-browser-runner#36]
### Request:
a way of specifying the filename of the `jasmine-browser.json` config file to be used

### Purpose:
- running with different browser configurations based on different environments
- running with multiple, different browser configurations concurrently (both using headless, local browsers as well as when using a remote selenium grid)

### Additional Notes:
- while it would be possible to swap in separate files similar to how Angular builds swap in production vs. dev environment configuration files, this would not work when running tests concurrently which would force running sequentially against each browser. when the application needs to be tested in current and current minus 1 versions of all major browsers this would result in a large increase in the test execution time.
- for my purposes, the location of the configuration file is not as important as simply being able to specify the name, but I could see value in allowing a full path to the file to be specified as this might make for cleaner root directories when using multiple configuration files

**Comment by sgravrock** [comment]
That's already supported via the `--config=` option.

**Comment by bicarbon8** [comment]
ah, apologies... had seen the documentation only referred to jasmine-browser.json and any usage of the config option pertained to jasmine config and not jasmine browser config so I missed that it was supported
