### ISSUE TITLE
How to configure web server for binary file fetching?

### ISSUE THREAD

**Issue by duvifn** [jasmine/jasmine-browser-runner#38]
Hi,
Probably I'm missing something but I couldn't find documentation for what is the best practice for solving it.
I'm using `jasmine-browser-runner` and I need to load external binary file in order to test application functionality.
Where should I place this file so that the web server jasmine is running with would be able to serve it?
How should I configure `support.json` for this file?
I've tried putting it `srcDir` but I couldn't access it from inside the spec.

Thank you very much!

**Comment by sgravrock** [comment]
That isn't currently supported. If https://github.com/jasmine/jasmine-browser-runner/issues/37 were implemented, you could probably add an Express middleware that serves your file. In the meantime, you might be able to serve it separately using something like `npx serve`.

**Comment by duvifn** [comment]
OK. Thanks.
So I'm leaving this issue open
