### ISSUE TITLE
Custom reporter for jasmine via jasmine-browser-runner?

### ISSUE THREAD

**Issue by bksglatz** [jasmine/jasmine-browser-runner#40]
Is there any way to get custom reporter for jasmine (like https://www.npmjs.com/package/jasmine-reporters) configured to be used with jasmine-browser-runner.

**Comment by bksglatz** [comment]
Im fine with using a ts/js file instead of a json file for configuration. I was  Can i just forward the path to the js file as i do it for the json file via the same parameter when running jasmine-browser-runner? 

Maybe consider extending the documentation. I wasn't able to find any information about how to add custom reporters or use a js configuration instead of json configuration or a list of all supported configuration values except those from the example file created during init. 

Thx for the fast response and help. I will let you know if i was able to get it running this way.

**Comment by bksglatz** [comment]
Okay... Forget what i have written about the documentation. I wasn't able to find it ;) My fault... Everyting there: https://jasmine.github.io/api/browser-runner/edge/Configuration.html

**Comment by bksglatz** [comment]
Loading the reporter this way works fine. However the reporter does not work anymore or not the way i want it to work. But now that i know how to load reporters i can write my own :)

**Comment by sgravrock** [comment]
I'm glad that worked.

There's some discussion about the structure and discoverability of config docs at https://github.com/jasmine/jasmine.github.io/issues/161 .
