### ISSUE TITLE
Is TLS supported?

### ISSUE THREAD

**Issue by joeyparrish** [jasmine/jasmine-browser-runner#42]
I need to test software that uses APIs only available in a browser over HTTPS connections.  Is there a way to provide TLS configuration to express to support this?

**Comment by sgravrock** [comment]
TLS isn't currently supported but it probably wouldn't be too hard to add, given that the underlying Express framework supports it. I'd be happy to review a pull request that adds that feature.

**Comment by joeyparrish** [comment]
I'm working on a PR now, including tests.

**Comment by joeyparrish** [comment]
I also need custom hostnames, so I may also try to create my own version of #43, which seems partly stuck on https issues anyway.
