### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by serk12** [jasmine/jasmine-browser-runner#44]
Hello, is there any way to integrate a code coverage for the browser code? I can't find any resource mentioning jasmine-browser.

**Comment by sgravrock** [comment]
I haven't actually tried this, but you could probably put something together by instrumenting your code with [babel-plugin-istanbul](https://github.com/istanbuljs/babel-plugin-istanbul), collecting coverage data in an `afterAll`, and implementing an API endpoint via [custom Express middleware](https://jasmine.github.io/api/browser-runner/2.3/Configuration.html#middleware) to write the report to disk.
