### ISSUE TITLE
Feature request: browser instance isolation per test suite / test case?

### ISSUE THREAD

**Issue by jayaddison** [jasmine/jasmine-browser-runner#57]
Hello,

### Background / context
I'm trying to develop some test cases where the JavaScript code-under-test creates somewhat-immutable datastructures, by declaring the relevant variables using the [`const` keyword](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const) in combination with [`Object.freeze`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze) and [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode) to prevent further modifications to their properties.

This introduces a conflict when trying to run test coverage that exercises multiple initial states for those structures -- because within a single suitable JavaScript engine instance, by design, only the first state will be successfully constructed; subsequent tests/fixtures that attempt to reconfigure it will fail since they cannot redeclare or adjust the existing objects.

### Minimal repro case
The following slightly-contrived minimal repro case demonstrates the problem; running either test case individually provides a successful result, but in combination they fail.

**Code-under-test (index.js)**
```javascript
"use strict";

function setModifiable(value) {
  state.modifiable = !!value;
  Object.freeze(state);
}

const state = {modifiable: true};
```

**Test suite (specs-index.js)**
```javascript
describe("A suite", function() {
    it("freezes an initially-mutable state", function() {
        setModifiable(true);
    });
    it("freezes an initially-immutable state", function() {
        setModifiable(false);
    });
});
```

**Test dependencies (package.json)**
```json
{
  "dependencies": {
    "jasmine-browser-runner": "2.5.0"
  }
}
```

**Repro script**
```shell
$ npm install
$ # the first two commands here report success; the third reports failure
$ npx jasmine-browser-runner runSpecs --config=jasmine-browser.mjs --filter=initially-mutable
$ npx jasmine-browser-runner runSpecs --config=jasmine-browser.mjs --filter=initially-immutable
$ npx jasmine-browser-runner runSpecs --config=jasmine-browser.mjs
```

I acknowledge that this problem isn't unique to Jasmine/the browser runner -- it'll apply to many JavaScript test runners that re-use the same engine instance to perform multiple tests (fairly standard practice, due to the resource overhead of tearing down and instantiating a fresh browser between tests).  Even so, I'd like to enquire about an isolation feature to handle this.

### Investigation
From inspection of `jasmine-browser-runner` (in particular the [`runSpecs` function](https://github.com/jasmine/jasmine-browser-runner/blob/bae95df56c39bbc747e03c3750954b8e21055846/index.js#L67-L144)), I don't think that it is currently possible to run each test within a separate, isolated fresh browser instance.

### Workaround
A local workaround that I've been able to use it to place the relevant tests into individual files, and then to write an external command-line driver script that uses `--filter` to run `jasmine-browser-runner` for each test/file.  This is fine, but it places some significant constraints on the layout of the test code.

### Existing issues
Issue #51 appears to be the closest existing bugreport to this one, though I think the use-case there is potentially different.  Some of the `jasmine-core` bugreports about problems where object lifetime spans different test cases would be hidden-or-resolved (depending on perspective) by this form of isolation.

Thanks!
James

**Comment by sgravrock** [comment]
My advice would be to refactor your code to decouple the parts you're trying to test from the parts that are problematic, to remove the global state, or both. The testing difficulty you're experiencing is providing feedback about some characteristics of your code that tend to be bad for maintainablity as well as for testing. I think it's better to listen to that feedback than to try to silence it.

You might disagree, and that's fine. But there's a zero-sum tradeoff between providing that kind of feedback and making it easier to test code that has tight coupling, global state, and other impediments. Most testing frameworks favor providing feedback, and Jasmine is no exception.

That's one of the reasons I'm skeptical about this proposal. The other is the performance impact. I still occasionally hear people who haven't used Jasmine in years complain about the one millisecond per spec overhead it used to have. What you're proposing would cost _two seconds_ per spec on my machine. Some numbers for the jasmine-core test suite:

* Actual suite run time: 0.5s (measured)
* `jasmine-browser-runner runSpecs`: 3s (measured). I estimate that about 0.5s of that is server startup. That leaves ~2 seconds spent starting and stopping the browser.
* `jasmine-browser-runner runSpecs` with per-test isolation: ~58 minutes (estimated based on the above numbers)
* `jasmine-browser-runner runSpecs` with per-file isolation: ~3.8 minutes (estimated based on the above numbers)

Nobody's going to accept that amount of overhead. There are faster approaches that provide less isolation, like doing a page load. But that's still likely to be too slow for most people. And for those who would accept that trade-off, there are plenty of end-to-end integration testing tools available that do just that.

If you still want to keep your state global and dependencies hardwired, there is one other option: You could move the immutable global itself into its own module, and then use [import maps](https://github.com/jasmine/jasmine-browser-runner?tab=readme-ov-file#es-module-support) to replace that module with a version that allows mutability.

**Comment by jayaddison** [comment]
Thanks @sgravrock for the thorough response - I agree that this could be a sign of limitations in the application structure, and that the testing performance overhead from browser-per-test is probably unacceptable in most (if not all) situations.  Thanks also for the import-maps and browser-refresh suggestions; I'll read more about those to find an alternative solution.
