### ISSUE TITLE
spec files in coffeescript

### ISSUE THREAD

**Issue by thimios** [jasmine/jasmine-browser-runner#8]
I have a rails 6 project that is using the asset pipeline. We have our spec files in coffeescript and have been using jasmine-gem that just supported coffescript specs since version 2(https://github.com/jasmine/jasmine-gem/blob/main/release_notes/v2.0.0.md).

Since the jasmine-gem is being deprecated we are migrating to jasmine-browser-runner as recommended in https://github.com/jasmine/jasmine-gem#deprecated but it seems that we cannot just specify our specFiles to be coffeescipt in jasmine-browser.json.

Is there a way to get coffeescript specs running with jasmine-browser-runner?

**Comment by sgravrock** [comment]
I don't have a recipe for coffeescript, but the general pattern is to generate browser-ready JS files on disk and then point jasmine-browser-runner at those. That might be as simple as running something like `coffee -c spec/javascripts/*.coffee`.

**Comment by thimios** [comment]
thanks for the workaround, yes it works!
