### ISSUE TITLE
[question] How to get the browser logs when running jasmine-browser-runner runSpecs

### ISSUE THREAD

**Issue by gparlakov** [jasmine/jasmine-browser-runner#9]
I'd like to get the logs from the browser console when running `jasmine-browser-runner runSpecs` for `chromeHeadless`. 

How can I do that?

**Comment by sgravrock** [comment]
Sorry, but there isn't currently a way to do that.

**Comment by gparlakov** [comment]
Hi. Thanks for the reply.

My goal was to output the console.log-s from tests. I guess that's not
possible.

**Comment by sgravrock** [comment]
Actually, it occurs to me that you could use `setSpecProperty` in combination with a custom reporter to do this. First, add a helper file `spec/helpers/logs.js`:

```
(function() {
   let logs = [];

   beforeAll(function() {
      spyOn(console, 'log').and.callFake(function() {
         logs.push(arguments);
      });
   });

   afterEach(function() {
      setSpecProperty('consoleLogs', logs);
      logs = [];
   });
}());
```

Then add a custom reporter in `reporter.js`:

```
const {DefaultReporter} = require('jasmine-browser-runner');

function Reporter() {
}
Reporter.prototype = new DefaultReporter();
const originalSpecDone = Reporter.prototype.specDone;

Reporter.prototype.specDone = function(info) {
   originalSpecDone.call(this, info);
   doSomethingWith(info.properties.consoleLogs);
}

module.exports = Reporter;
```

(Yes, the reporter setup is awkward. I'm looking to improve that.)

Finally, add `  "reporters": ["./reporter.js"],` to `spec/support/jasmine.json`.

The drawback is that you won't capture console.log messages that occur between specs. That can come up when an async spec signals completion before it's actually done, or when a `beforeAll` or `afterAll` causes something to be logged.

**Comment by gparlakov** [comment]
Thanks for the tip! I'll try that.

I'm doing a Jasmine testing course so that should come in handy.

**Comment by gparlakov** [comment]
Hey, @sgravrock thanks a bunch. It works just like you said.


I went with :

```js
const { DefaultReporter } = require('jasmine-browser-runner');

function Reporter() {}
Reporter.prototype = new DefaultReporter();
const originalSpecDone = Reporter.prototype.specDone;

Reporter.prototype.specDone = function (info) {
  // originalSpecDone.call(this, info) // just adds a '.' in the output for a passed test
  if (Array.isArray(info.properties.consoleLogs)) {
    info.properties.consoleLogs.forEach((a) => console.log(...a));
  }
  delete info.properties.consoleLogs;
};

module.exports = Reporter;
```
for reporter.js

and 

```js
(function () {
  let logs = [];

  beforeAll(function () {
    const originalLog = console.log;
    spyOn(console, 'log').and.callFake(function () {
      logs.push(arguments);
      originalLog.call(console, arguments);
    });
  });

  afterEach(function () {
    setSpecProperty('consoleLogs', logs);
    logs = [];
  });
})();

```

**Comment by ryanb** [comment]
Note `DefaultReporter` was renamed to `ConsoleReporter` so you'll need to replace it in the reporter code above if you want to use it today.

**Comment by gparlakov** [comment]
Thanks for the heads up!

**Comment by ryanb** [comment]
Another suggestion: if you also run tests in non-headless mode the console log messages will look strange with the console.log override. You can check `if (navigator.webdriver)` in `logs.js` to only override console.log when it's running in headless mode.

```js
(function () {
  if (navigator.webdriver) {
    let logs = [];

    beforeAll(function () {
      const originalLog = console.log;
      spyOn(console, "log").and.callFake(function () {
        logs.push(arguments);
        originalLog.call(console, arguments);
      });
    });

    afterEach(function () {
      setSpecProperty("consoleLogs", logs);
      logs = [];
    });
  }
})();
```
